name: Run Selenium On GitHub Action
on:
  push:
    
jobs:
  scrape:
    runs-on: windows-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Installing package list
        run: pip install selenium    
        
      - name: Running the Python script
        run: python CAD_EOI_test.py

     